/** What each thing that is written down is called, as a person would say it. One with no words here is shown by its name. */
export const WORDS: Record<string, string> = {
  'account.setup': 'Set this Homewarp up',
  'account.sign_in': 'Signed in',
  'account.sign_in_failed': 'Tried to sign in, and was refused',
  'account.sign_out': 'Signed out',
  'account.create': 'Made an account',
  'account.remove': 'Removed an account',
  'account.password': 'Changed a password',
  'account.two_steps_on': 'Turned two-step sign-in on',
  'account.two_steps_off': 'Turned two-step sign-in off',
  'account.passkey_add': 'Added a passkey',
  'account.passkey_remove': 'Removed a passkey',
  'template.import': 'Imported a template',
  'template.remove': 'Removed a template',
  'server.create': 'Made the server',
  'server.change': 'Changed its settings',
  'server.icon': 'Changed its icon',
  'server.remove': 'Removed the server',
  'server.start': 'Started it',
  'server.stop': 'Stopped it',
  'server.kill': 'Killed it',
  'server.crash': 'It crashed',
  'server.gave_up': 'Gave up starting it again',
  'server.sleep': 'Put it to sleep',
  'server.wake': 'Woke it for a player',
  'server.install': 'Installed it again',
  'server.command': 'Typed a command',
  'server.let_in': 'Let an account in',
  'server.turn_out': 'Took an account out',
  'mods.install': 'Installed a mod',
  'files.write': 'Wrote a file',
  'files.download': 'Downloaded a file',
  'files.folder': 'Made a folder',
  'files.move': 'Moved a file',
  'files.remove': 'Deleted files',
  'files.pack': 'Packed files',
  'files.unpack': 'Unpacked an archive',
  'backup.create': 'Made a backup',
  'backup.restore': 'Put a backup back',
  'backup.copy': 'Copied a backup to the store',
  'backup.copy_failed': 'A backup was not copied to the store',
  'backup.remove': 'Deleted a backup',
  'backup.download': 'Downloaded a backup',
  'backup.keep': 'Changed how many backups are kept',
  'schedule.ran': 'A schedule ran',
  'schedule.create': 'Made a schedule',
  'schedule.change': 'Changed a schedule',
  'schedule.remove': 'Removed a schedule',
  'schedule.run': 'Ran a schedule by hand',
  'sftp.sign_in': 'Signed in over SFTP',
  'sftp.sign_in_failed': 'Tried to sign in over SFTP, with the wrong password',
  'settings.change': 'Changed a setting',
  'webhook.create': 'Made a webhook',
  'webhook.change': 'Changed a webhook',
  'webhook.remove': 'Removed a webhook',
  'template.fetch': 'Fetched an egg',
  'catalogue.fetch': 'Fetched the catalogue',
  'gate.connect': 'Started connecting a VPS',
  'gate.check': 'Checked the tunnel',
  'gate.disconnect': 'Disconnected a VPS',
  'gate.rename': 'Renamed a VPS',
  'update.available': 'A newer Homewarp is out',
  'update.channel': 'Changed which releases are taken',
  'update.install': 'Began an update',
  'update.done': 'Homewarp was updated',
  'update.failed': 'An update did not start',
  'gate.lost': 'A VPS stopped answering',
  'gate.back': 'A VPS answered again',
  'gate.harden': 'Hardened the VPS, on trial',
  'gate.harden_keep': 'Kept the VPS hardened',
  'gate.unharden': 'Took the guard off the VPS',
  'panel.name': 'Gave the panel a name',
  'panel.ask': 'Asked for the panel’s certificate again',
  'panel.certificate': 'Got a certificate for the panel',
}

/** What the things that are written down are listed under, by the first half of their names. */
const GROUPS: Record<string, string> = {
  server: 'Servers',
  files: 'Files',
  mods: 'Mods',
  backup: 'Backups',
  schedule: 'Schedules',
  gate: 'VPS',
  panel: 'The panel',
  update: 'Updates',
  account: 'Accounts',
  sftp: 'Accounts',
  template: 'Templates',
  catalogue: 'Templates',
  settings: 'Settings',
  webhook: 'Settings',
}

/** The heading a thing that is written down belongs under. One that has none is under the first half of its name. */
export function groupOf(action: string): string {
  const first = action.split('.')[0] ?? action
  return GROUPS[first] ?? first
}
